// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRUI9-PLtUPJvKlGoOkcUz_6TRzT_aq3M',
    appId: '1:911815887027:android:a694bab29cbdb6c2ddc8c6',
    messagingSenderId: '911815887027',
    projectId: 'flutter-product-project-0003',
    databaseURL: 'https://flutter-product-project-0003-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-product-project-0003.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC30kv-QbhQNADXRsnOQ5ODH6Uw3GYxtrA',
    appId: '1:911815887027:ios:a0e0e548bd525553ddc8c6',
    messagingSenderId: '911815887027',
    projectId: 'flutter-product-project-0003',
    databaseURL: 'https://flutter-product-project-0003-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-product-project-0003.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectProduct',
  );
}
